#!/bin/bash
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
XAUTHORITY=$HOME/.Xauthority
export XAUTHORITY 
LANG=es_ES.UTF-8 
export LANG
echo $$ > /tmp/xsession.pid 
dbus-launch --exit-with-session startxfce4 &
